-- Enable pgvector extension for vector similarity search
CREATE EXTENSION IF NOT EXISTS vector;

-- Add embedding column to notes table
-- Using 768 dimensions to match Gemini text-embedding-004 model
ALTER TABLE notes 
ADD COLUMN embedding vector(768);

-- Create index for fast similarity search using HNSW algorithm
-- HNSW (Hierarchical Navigable Small World) is better for high-dimensional vectors
CREATE INDEX notes_embedding_idx ON notes 
USING hnsw (embedding vector_cosine_ops);

-- Function to search notes by semantic similarity
CREATE OR REPLACE FUNCTION search_notes_by_similarity(
    query_embedding vector(768),
    target_chapter_id UUID,
    result_limit INTEGER DEFAULT 5
)
RETURNS TABLE (
    note_id UUID,
    title TEXT,
    content TEXT,
    similarity FLOAT
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        notes.id,
        notes.title,
        notes.content,
        1 - (notes.embedding <=> query_embedding) AS similarity
    FROM notes
    WHERE 
        notes.chapter_id = target_chapter_id
        AND notes.embedding IS NOT NULL
        AND notes.approval_status = 'approved'
        AND notes.visibility = 'public'
    ORDER BY notes.embedding <=> query_embedding
    LIMIT result_limit;
END;
$$ LANGUAGE plpgsql;

-- Add comment for documentation
COMMENT ON COLUMN notes.embedding IS 'Vector embedding (768-dim) generated by Gemini text-embedding-004 for semantic search';
COMMENT ON FUNCTION search_notes_by_similarity IS 'Search notes by semantic similarity using cosine distance';
